"""initial models

Revision ID: 185510e16918
Revises: 79b1a74fbff2
Create Date: 2023-10-19 09:30:10.246823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185510e16918'
down_revision = '79b1a74fbff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('location_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_type_id'], ['location_types.id'], name=op.f('fk_locations_location_type_id_location_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_location_features_location_id_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_reports_location_id_locations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reported_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('location_feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_feature_id'], ['location_features.id'], name=op.f('fk_reported_features_location_feature_id_location_features')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_reported_features_report_id_reports')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reported_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_reported_photos_report_id_reports')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reported_photos')
    op.drop_table('reported_features')
    op.drop_table('reports')
    op.drop_table('location_features')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('location_types')
    # ### end Alembic commands ###
