"""add propelauth email to User model

Revision ID: 447e950514a7
Revises: f713d000303b
Create Date: 2023-11-09 02:30:32.475510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447e950514a7'
down_revision = 'f713d000303b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propelauth_email', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint('propelauth_email', ['propelauth_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('propelauth_email')

    # ### end Alembic commands ###
