"""propelauth integration

Revision ID: 49b315816710
Revises: 93ed8acdbd2a
Create Date: 2023-11-08 22:43:35.975083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b315816710'
down_revision = '93ed8acdbd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propelauth_user_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_propelauth_user_id', ['propelauth_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('propelauth_user_id')

    # ### end Alembic commands ###
