"""add feature table to hold predefined features

Revision ID: 532802755a89
Revises: bb68b2e0c05b
Create Date: 2023-10-24 21:30:58.234906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532802755a89'
down_revision = 'bb68b2e0c05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_location_features_feature_id_features'), 'features', ['feature_id'], ['id'])
        batch_op.drop_column('feature')

    with op.batch_alter_table('reported_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_reported_features_location_feature_id_location_features', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reported_features_feature_id_features'), 'features', ['feature_id'], ['id'])
        batch_op.drop_column('location_feature_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reported_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_feature_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_reported_features_feature_id_features'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reported_features_location_feature_id_location_features', 'location_features', ['location_feature_id'], ['id'])
        batch_op.drop_column('feature_id')

    with op.batch_alter_table('location_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_location_features_feature_id_features'), type_='foreignkey')
        batch_op.drop_column('feature_id')

    op.drop_table('features')
    # ### end Alembic commands ###
